#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ansible-galaxy collection install community.general ansible.posix community.crypto kewlfft.aur
ansible-playbook -K $SCRIPT_DIR/setup.yml
