# Gruvbox dark color palette
$color0 = rgb(40, 40, 40)       # bg
$color1 = rgb(204, 36, 29)      # red
$color2 = rgb(152, 151, 26)     # green
$color3 = rgb(215, 153, 33)     # yellow
$color4 = rgb(69, 133, 136)     # blue
$color5 = rgb(177, 98, 134)     # purple
$color6 = rgb(104, 157, 106)    # aqua
$color7 = rgb(168, 153, 132)    # fg4 / gray

background {
    monitor =
    path = $HOME/.config/wallpapers/ct1wtm4x2wae1.png
    color = $color7
    blur_size = 5
    blur_passes = 0
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 1.00
    dots_center = true
    outer_color = $color0
    inner_color = $color0
    font_color = $color7
    fade_on_empty = true
    placeholder_text = <i>Gimme some alphanumerics senpai!...</i>
    hide_input = false
    position = 0, 60
    halign = center
    valign = bottom
}

label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    color = white
    font_size = 128
    font_family = IBM Plex Sans Medium 10
    position = 0, 20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = white
    font_size = 128
    font_family = IBM Plex Sans Medium 10
    position = 0, -140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%d %b") </big></b>"
    color = $color3
    font_size = 16
    font_family = IBM Plex Sans Medium 10
    position = 0, -160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%A") </big></b>"
    color = $color3
    font_size = 16
    font_family = IBM Plex Sans Medium 10
    position = 0, -180
    halign = center
    valign = center
}
