theme = "theme"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w"
esc = ["collapse_selection","keep_primary_selection"]

C-e = ":sh tmux new-window -n fx '~/.config/helix/yazi-picker.sh open'"
